import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div class="container flex justify-between bg-gray-100 pb-5">
               <div className="mx-5 mt-4">
                   <img src="https://www.provast.in/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdj7nomqfd%2Fimage%2Fupload%2Fv1652909540%2Fpvast_B_fpwhlu.png&w=1920&q=75" width="170" height="170"/>
               </div>
               <div>
                    <ul className="flex justify-between mt-4 mx-3">
                      <li className="p-4 hover:text-orange-600 cursor-pointer">Resumes</li>
                      <li className="p-4 hover:text-orange-600 cursor-pointer"><a href="/testpatterns">Test Patterns</a></li>
                      <li className="p-4 hover:text-orange-600 cursor-pointer">Open Jobs</li>
                    </ul>
               </div>
               <div className="flex justify-between mr-6">
                   <button className="text-gray-400 px-3 border-gray-400 mx-4 hover:text-gray-500">Login</button>
                   <button  className="text-gray-600 px-3 border-gray-400 mx-4 hover:text-gray-700" >Signup</button>
               </div>
          </div>
      </main>
    </>
  )
}
