import Head from 'next/head'
import AdminNavbar from '@/components/admin_navbar'
import Testpatternsadd from '@/components/test_patterns_add'
import SectionsPatternsadd from '@/components/sections_pattern_add'
export default function Home() {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <AdminNavbar></AdminNavbar>
          <div class="container mx-6">
            <h1 className="text-gray-600 text-center my-6 text-2xl">Add Company Test Patterns</h1>
              <Testpatternsadd></Testpatternsadd>
          </div>
      </main>
    </>
  )
}
